# Generated by Django 3.2.25 on 2024-07-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='timestamps',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='timestamps',
            new_name='timestamp',
        ),
    ]
